sudo: required

language: python

services:
  - docker

before_install:
- docker pull lalu/flask-demo-app
- docker build -t flask-demo-app .
- docker run -d --name webapp flask-demo-app
- docker ps -a

script:
- docker exec app python -m unittest discover

after_script:
- docker rm -f app
